#!/data/data/com.termux/files/usr/bin/sh
export PATH="$PREFIX/bin:$PATH"
export PYTHONPATH="$HOME/HormigasAIS-video-intelligence-checker/backend"

# Cambiar al directorio backend
cd "$HOME/HormigasAIS-video-intelligence-checker/backend" || exit 1

# Activar entorno virtual
. venv/bin/activate

# Ejecutar Uvicorn con logs visibles para runit
exec uvicorn api:app --host 0.0.0.0 --port 8000 --log-level info
