#!/data/data/com.termux/files/usr/bin/sh
export PATH=$PREFIX/bin:$PATH
export PYTHONPATH=/data/data/com.termux/files/home/HormigasAIS-video-intelligence-checker/backend

cd /data/data/com.termux/files/home/HormigasAIS-video-intelligence-checker/backend

# Activar entorno virtual
. venv/bin/activate

# Iniciar Uvicorn
exec uvicorn main:app --host 0.0.0.0 --port 8000
